version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: library-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network

  backend:
    build: ./backend
    container_name: library-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/library_management
    networks:
      - library-network

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - library-network

volumes:
  mongodb_data:

networks:
  library-network:
    driver: bridge